import type {
  ConditionId,
  ConditionMetadata,
  ModifierId,
  ModifierMetadata,
} from "../types/parameter";

export const MODIFIER_METADATA: Record<ModifierId, ModifierMetadata> = {
  NONE: { label: "None" },
  ABS_BOTH: { label: "Absolute (Z)" },
  ABS_X: { label: "Absolute Real" },
  ABS_Y: { label: "Absolute Imaginary" },
  CONJUGATE: { label: "Conjugate" },
  REVERSE: { label: "Reverse" },
  INVERT: { label: "Invert" },
  SIN: { label: "Sin" },
  COS: { label: "Cos" },
  TAN: { label: "Tan" },
  SINH: { label: "Sinh" },
  COSH: { label: "Cosh" },
  TANH: { label: "Tanh" },
  EXP: { label: "Exponential" },
  LOG: { label: "Logarithm" },
  SQRT: { label: "Sqrt" },
  RECIPROCAL: { label: "Reciprocal" },
  POW3: { label: "Cubic" },
  FOLD: { label: "Fold" },
  SWIZZLE: { label: "Swizzle" },
  KALEIDOSCOPE: { label: "Kaleidoscope" },
  POLAR: { label: "Polar" },
  SPHERE_INVERSION: { label: "Sphere Inversion" },
  TILE: { label: "Tile" },
  CREASE: { label: "Crease (Diagonal)" },
  SAWTOOTH: { label: "Sawtooth (Grid)" },
  WAVEFOLD: { label: "Wavefold (Organic)" },
  SHIFT_INVERT: { label: "Shift Invert" },
  VOXELIZE: { label: "Voxelize (Pixels)" },
  TAN_WARP: { label: "Tangent Warp" },
  CROSS_FOLD: { label: "Cross-Fold" },
  SPIRAL: { label: "Log Spiral" },
  CIRCLE_PULSE: { label: "Circle Pulse" },
  GLITCH: { label: "The Glitch" },
};

export const CONDITION_METADATA: Record<ConditionId, ConditionMetadata> = {
  ALWAYS: { label: "Always" },
  Z_REAL_POSITIVE: { label: "if Re(z) > 0" },
  Z_IMAG_POSITIVE: { label: "if Im(z) > 0" },
  Z_MAG_GT_1: { label: "if |z| > 1" },
  Z_ANGLE_POSITIVE: { label: "if arg(z) > 0" },
  Z_REAL_GT_IMAG: { label: "if Re(z) > Im(z)" },
  Z_ABS_REAL_GT_ABS_IMAG: { label: "if |Re(z)| > |Im(z)|" },
};
